package serr

import (
	"fmt"
)

var (
	// ErrNilPointer defines a nil pointer argument error.
	ErrNilPointer = fmt.Errorf("invalid nil pointer")

	// ErrConversion defines a type conversion error.
	ErrConversion = fmt.Errorf("invalid type conversion")

	// ErrServiceNotFound defines a service not found on the container.
	ErrServiceNotFound = fmt.Errorf("service not found")

	// ErrConfigSourceNotFound defines a source sconfig source not found error.
	ErrConfigSourceNotFound = fmt.Errorf("sconfig source not found")

	// ErrDuplicateConfigSource defines a duplicate sconfig source
	// registration attempt.
	ErrDuplicateConfigSource = fmt.Errorf("sconfig source already registered")

	// ErrConfigPathNotFound defines a path in Partial not found error.
	ErrConfigPathNotFound = fmt.Errorf("sconfig path not found")

	// ErrConfigRestPathNotFound defines a sconfig path not found error.
	ErrConfigRestPathNotFound = fmt.Errorf("rest path not found")

	// ErrInvalidConfigDecoderFormat defines an error that signal an
	// unexpected/unknown sconfig source decoder format.
	ErrInvalidConfigDecoderFormat = fmt.Errorf("invalid sconfig decoder format")

	// ErrInvalidConfigSourceType defines an error that signal an
	// unexpected/unknown sconfig source type.
	ErrInvalidConfigSourceType = fmt.Errorf("invalid sconfig source type")

	// ErrInvalidConfigSourcePartial defines an error that signal an
	// invalid source configuration Partial.
	ErrInvalidConfigSourcePartial = fmt.Errorf("invalid sconfig source sconfig")

	// ErrInvalidLogFormat defines an error that signal an invalid
	// slog format.
	ErrInvalidLogFormat = fmt.Errorf("invalid output format")

	// ErrInvalidLogLevel defines an error that signal an invalid
	// slog level.
	ErrInvalidLogLevel = fmt.Errorf("invalid logger level")

	// ErrDuplicateLogStream defines an error that signal that the
	// requested slog stream to be registered have an id of an already
	// registered slog stream.
	ErrDuplicateLogStream = fmt.Errorf("stream already registered")

	// ErrInvalidLogStreamType defines an error that signal that the
	// requested stream was unable to be generated by the requested type.
	ErrInvalidLogStreamType = fmt.Errorf("invalid stream type")

	// ErrInvalidLogStreamConfig defines an error that signal that the
	// given slog stream configuration was unable to be parsed correctly
	// enabling the slog stream generation.
	ErrInvalidLogStreamConfig = fmt.Errorf("invalid slog stream sconfig")

	// ErrDatabaseConfigNotFound defines an error that signal that the
	// configuration to the requested database connection was not found.
	ErrDatabaseConfigNotFound = fmt.Errorf("database sconfig not found")

	// ErrUnknownDatabaseDialect defines an error that signal that the
	// requested database connection configured dialect is unknown.
	ErrUnknownDatabaseDialect = fmt.Errorf("unknown database dialect")
)
